const ROLES = {
  ENTERPRISE: "Enterprise",
  AGENCY: "Agency",
  ADMIN: "Admin",
  SKRIBE: "Skribe",
  FREEBIES: "Freebies",
};
const allRoles = [
  ROLES?.ENTERPRISE,
  ROLES?.AGENCY,
  ROLES?.ADMIN,
  ROLES?.SKRIBE,
  ROLES?.FREEBIES,
];
const allRolesWithFreebies = [...allRoles, ROLES?.FREEBIES];
export const PERMISSION = {
  proList: allRoles,
  viewList: allRoles,
  brandDashboard: [ROLES?.ENTERPRISE],
  landingPage: allRoles,
  homePage: allRoles,
  dashboard: allRolesWithFreebies,
  X: allRoles,
  instagram: allRoles,
  journalistProfileDetail: allRolesWithFreebies,
  beatWatchIdName: allRoles,
  dashboardId: allRoles,
  brandReportId: allRoles,
  pressReleaseForm: allRoles,
  influencerId: allRoles,
  spokespersonId: allRoles,
  journalistSearch: allRolesWithFreebies,
  mediaTypes: allRoles,
  mediaTypeOutletIdName: allRolesWithFreebies,
  journalistByBeatSelected: allRoles,
  geoCityId: allRoles,
  geoByJourno: allRoles,
  campaignManager: allRoles,
  mediaLists: allRoles,
  campaignListId: allRoles,
  listTrackingId: allRoles,
  campaignAction: allRoles,
  journalistByOutletIdName: allRolesWithFreebies,
  journalistByAnchorIdName: allRoles,
  journalistByProducersIdName: allRoles,
  journalistByShowsIdName: allRoles,
  byShowJournalistsShowNameOutletId: allRoles,
  journoByShowId: allRoles,
  outletEditorOutletIdName: allRolesWithFreebies,
  bureauChiefOutletIdName: allRolesWithFreebies,
  columnistOutletIdName: allRoles,
  supplementsOutletIdName: allRoles,
  supplementsJournoSupplementName: allRoles,
  supplementJournoOutletIdName: allRoles,
  internationalOutletIdName: allRoles,
  instaDetailInsta: allRoles,
  podcast: allRoles,
  podcastListingId: allRoles,
  podcastDetailId: allRoles,
  topicsDetail: allRoles,
  topicsReport: allRoles,
  spokesperson: allRoles,
  influencer: allRoles,
  brandReport: allRoles,
  myCRM: allRoles,
  customCRM: allRoles,
  changePassword: allRoles,
  accountSettings: allRoles,
  esg: allRoles,
  spokesPerson: allRoles,
  brand: allRoles,
  topics: allRoles,
  competitors: allRoles,
  beats: allRoles,
  allMediaTypes: allRoles,
  geoLocation: allRoles,
  favorites: allRoles,
  skribe365: allRoles,
  skribe365Login: allRoles,
  teaTimeLogin: allRoles,
  beatWatch: allRoles,
  beatWatchPage: allRoles,
  errorPage: allRolesWithFreebies,
  campaginSummary: allRoles,
  chooseTemplate: allRoles,
  introTemplate: allRoles,
  updateCampaign: allRoles,
  templatePreview: allRoles,
  campaignDetail: allRoles,
  createCampaign: allRoles,
  campaignLanding: allRoles,
  regional: allRoles,
  regionalShowMedia: allRoles,
  PressReleaseDistribution: allRoles,
  advanceSearch: allRoles,
  advanceSearchQuery: allRoles,
  brandStory: allRoles,
  brandStoryExplore: allRoles,
  brandStoryUpgrades: allRoles,
  disclaimerbrandStory: allRoles,
};
